#!/usr/bin/env bash

echo java-custom-runtime start

ls -la
ls -la ./lambda-custom-java-runtime/

echo ${AWS_LAMBDA_RUNTIME_API}

JAVA=./lambda-custom-java-runtime/bin/java
EXECUTABLE=java-custom-runtime.jar

${JAVA} -version

${JAVA} Exec

${JAVA} -p ${EXECUTABLE} -m lambda.example
